name: Build

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run build script
        id: runBuild
        run: ./Build.ps1
        shell: pwsh -File "{0}"

      - uses: actions/upload-artifact@v3
        with:
          name: node-gyp-for-windows
          path: ./node-gyp-for-windows.7z
